FROM base AS kubectl
# renovate: datasource=github-releases depName=kubernetes/kubernetes
ARG KUBERNETES_VERSION=v1.20.2
RUN curl --silent --location --output /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v${KUBERNETES_VERSION}/bin/linux/amd64/kubectl \
 && chmod +x /usr/local/bin/kubectl
