FROM base AS helm
# renovate: datasource=github-releases depName=helm/helm
ENV HELM_VERSION=3.5.1
RUN curl --silent --location "https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz" | \
        tar -xvzC /usr/local/bin/ --strip-components=1 linux-amd64/helm
